services:
  python:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "uv sync && bash"

  python-dev:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: sleep infinity
    stdin_open: true
    tty: true
    profiles: ["dev"]

  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - JUPYTER_TOKEN=simple-token-123
    command: uv run jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --notebook-dir=/app
    profiles: ["jupyter"]