name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"
    
    - name: Set up Python
      run: uv python install
    
    - name: Install dependencies
      run: uv sync --all-extras --dev
    
    - name: Build Jupyter environment
      run: echo "Jupyter setup complete"

  docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t uv-docker-project .
    
    - name: Test Docker image
      run: |
        docker run --rm -d -p 8888:8888 --name test-jupyter uv-docker-project
        sleep 10
        docker logs test-jupyter
        docker stop test-jupyter